apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: coredns-udp
  name: coredns-udp
  namespace: external-dns
spec:
  type: LoadBalancer
  loadBalancerIP: {{ LoadBalancer_IP }}
  ports:
  - name: dns
    port: 53
    protocol: UDP
  selector:
    k8s-app: coredns
