apiVersion: v1
kind: Service
metadata:
  name: coredns-tcp
  namespace: external-dns
  labels:
    k8s-app: coredns-tcp
spec:
  type: LoadBalancer
  loadBalancerIP: {{ LoadBalancer_IP }}
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
  selector:
    k8s-app: coredns
